export const FORM_LIST_SUCCESS = "FORM_LIST_SUCCESS";
export const FORM_LIST_FAILURE = "FORM_LIST_FAILURE";

/////////////

export const FORM_LIST_OBJ_SUCCESS = "FORM_LIST_OBJ_SUCCESS";
export const FORM_LIST_OBJ_FAILURE = "FORM_LIST_OBJ_FAILURE";
